### ISSUE TITLE
Automatic deploy script

### ISSUE THREAD

**Issue by nightpool** [Genius/cache_rails_assets_buildpack#1]
Right now, deploying this buildpack requires 

1) making a branch & tag
2) changing bin/compile
3) making a new branch, committing
4) making ANOTHER tag
5) pushing to github

Ideally, we'd have a script that handles 1-5 for us

**Comment by natekandler** [comment]
I've added a `rake` task that automatically creates versioned `save` and `restore` releases.

When `rake release` is run it will:
* Use a template to create the `compile` file
* Commit the change and create a release
* Remove the commit that created the release to keep a clean history

![Screen Shot 2019-09-19 at 7 18 32 AM](https://user-images.githubusercontent.com/6255992/65252443-d3419a00-daad-11e9-96e4-24abb0f62f0c.png)

**Comment by nightpool** [comment]
(closing because done :D)
